language: python

sudo: required

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer python3
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - ONLINE=1 ./bau test

after_script:
  - codecov
