language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - NEO4J_VERSION="1.8.3"
  - NEO4J_VERSION="1.9.8"
  - NEO4J_VERSION="2.0.4"
  - NEO4J_VERSION="2.1.3"

before_install:
  - . .travis/neo.sh
  - ./lib/neo4j/bin/neo4j start || ( cat ./lib/neo4j/data/log/*.log && exit 1 )

install:
  - pip install -r .travis/requirements.txt

script:
  - py.test ./test
